# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\resolve\Python\rs_resolve\tool\copy_text_plus\copy_text_plus.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\resolve\Python\rs_resolve\tool\copy_text_plus\copy_text_plus.ui' applies.
#
# Created: Tue Jun 13 06:08:39 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(358, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.trackGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackGroupBox.sizePolicy().hasHeightForWidth())
        self.trackGroupBox.setSizePolicy(sizePolicy)
        self.trackGroupBox.setObjectName("trackGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.trackGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.trackGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sourceComboBox = QtWidgets.QComboBox(self.trackGroupBox)
        self.sourceComboBox.setObjectName("sourceComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sourceComboBox)
        self.label_2 = QtWidgets.QLabel(self.trackGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.destinationComboBox = QtWidgets.QComboBox(self.trackGroupBox)
        self.destinationComboBox.setObjectName("destinationComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.destinationComboBox)
        self.swapButton = QtWidgets.QPushButton(self.trackGroupBox)
        self.swapButton.setObjectName("swapButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.swapButton)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.updateButton = QtWidgets.QPushButton(self.trackGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateButton.sizePolicy().hasHeightForWidth())
        self.updateButton.setSizePolicy(sizePolicy)
        self.updateButton.setMinimumSize(QtCore.QSize(50, 30))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.trackGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setMinimumSize(QtCore.QSize(80, 30))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.loadButton = QtWidgets.QPushButton(self.groupBox)
        self.loadButton.setMinimumSize(QtCore.QSize(80, 30))
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_3.addWidget(self.loadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copyButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton.setMinimumSize(QtCore.QSize(50, 30))
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout.addWidget(self.copyButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(50, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.trackGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Video Track", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Source", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Destination", None, -1))
        self.swapButton.setText(QtWidgets.QApplication.translate("MainWindow", "▲▼", None, -1))
        self.updateButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "トラック更新", None, -1))
        self.updateButton.setText(QtWidgets.QApplication.translate("MainWindow", "update", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "exclusion", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("MainWindow", "save", None, -1))
        self.loadButton.setText(QtWidgets.QApplication.translate("MainWindow", "load", None, -1))
        self.copyButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "トラック更新", None, -1))
        self.copyButton.setText(QtWidgets.QApplication.translate("MainWindow", "copy", None, -1))
        self.closeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "閉じる", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

