# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\bake_tool\bake_tool.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\bake_tool\bake_tool.ui' applies.
#
# Created: Tue Apr 25 10:54:34 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(334, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sfSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.sfSpinBox.setMinimum(-999999999)
        self.sfSpinBox.setMaximum(999999999)
        self.sfSpinBox.setObjectName("sfSpinBox")
        self.horizontalLayout_2.addWidget(self.sfSpinBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.efSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.efSpinBox.setMinimum(-999999999)
        self.efSpinBox.setMaximum(999999999)
        self.efSpinBox.setObjectName("efSpinBox")
        self.horizontalLayout_2.addWidget(self.efSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.globalRangeButton = QtWidgets.QPushButton(self.groupBox)
        self.globalRangeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.globalRangeButton.setObjectName("globalRangeButton")
        self.horizontalLayout.addWidget(self.globalRangeButton)
        self.renderRangeButton = QtWidgets.QPushButton(self.groupBox)
        self.renderRangeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.renderRangeButton.setObjectName("renderRangeButton")
        self.horizontalLayout.addWidget(self.renderRangeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.readButton = QtWidgets.QPushButton(self.centralwidget)
        self.readButton.setMinimumSize(QtCore.QSize(80, 30))
        self.readButton.setObjectName("readButton")
        self.horizontalLayout_4.addWidget(self.readButton)
        self.bakeButton = QtWidgets.QPushButton(self.centralwidget)
        self.bakeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.bakeButton.setObjectName("bakeButton")
        self.horizontalLayout_4.addWidget(self.bakeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setArrowType(QtCore.Qt.DownArrow)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_4.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_4.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Range", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Start Frame", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "End Frame", None, -1))
        self.globalRangeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Global Range", None, -1))
        self.renderRangeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Render Range", None, -1))
        self.readButton.setText(QtWidgets.QApplication.translate("MainWindow", "read", None, -1))
        self.bakeButton.setText(QtWidgets.QApplication.translate("MainWindow", "bake", None, -1))
        self.minimizeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "最小化", None, -1))
        self.minimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

