# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\number_tool\number_tool.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\number_tool\number_tool.ui' applies.
#
# Created: Fri Feb 17 00:30:43 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(341, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l2rRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.l2rRadioButton.setChecked(True)
        self.l2rRadioButton.setObjectName("l2rRadioButton")
        self.horizontalLayout_3.addWidget(self.l2rRadioButton)
        self.randomRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.randomRadioButton.setObjectName("randomRadioButton")
        self.horizontalLayout_3.addWidget(self.randomRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(280, 80))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.alignRButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignRButton.sizePolicy().hasHeightForWidth())
        self.alignRButton.setSizePolicy(sizePolicy)
        self.alignRButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignRButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignRButton.setFont(font)
        self.alignRButton.setStyleSheet("font:24pt \"メイリオ\";")
        self.alignRButton.setObjectName("alignRButton")
        self.gridLayout_2.addWidget(self.alignRButton, 0, 2, 1, 1)
        self.alignLButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLButton.sizePolicy().hasHeightForWidth())
        self.alignLButton.setSizePolicy(sizePolicy)
        self.alignLButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignLButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignLButton.setFont(font)
        self.alignLButton.setStyleSheet("font:24pt \"メイリオ\";")
        self.alignLButton.setObjectName("alignLButton")
        self.gridLayout_2.addWidget(self.alignLButton, 0, 0, 1, 1)
        self.distributeButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distributeButton.sizePolicy().hasHeightForWidth())
        self.distributeButton.setSizePolicy(sizePolicy)
        self.distributeButton.setMinimumSize(QtCore.QSize(45, 45))
        self.distributeButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.distributeButton.setFont(font)
        self.distributeButton.setStyleSheet("font:16pt \"メイリオ\";")
        self.distributeButton.setObjectName("distributeButton")
        self.gridLayout_2.addWidget(self.distributeButton, 0, 3, 1, 1)
        self.alignCButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignCButton.sizePolicy().hasHeightForWidth())
        self.alignCButton.setSizePolicy(sizePolicy)
        self.alignCButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignCButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignCButton.setFont(font)
        self.alignCButton.setStyleSheet("font: 16pt \"メイリオ\";")
        self.alignCButton.setObjectName("alignCButton")
        self.gridLayout_2.addWidget(self.alignCButton, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.absoluteRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.absoluteRadioButton.setChecked(True)
        self.absoluteRadioButton.setObjectName("absoluteRadioButton")
        self.horizontalLayout_4.addWidget(self.absoluteRadioButton)
        self.relativeRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.relativeRadioButton.setObjectName("relativeRadioButton")
        self.horizontalLayout_4.addWidget(self.relativeRadioButton)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.valueLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.valueLineEdit.setObjectName("valueLineEdit")
        self.gridLayout.addWidget(self.valueLineEdit, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.setButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setButton.sizePolicy().hasHeightForWidth())
        self.setButton.setSizePolicy(sizePolicy)
        self.setButton.setMinimumSize(QtCore.QSize(60, 56))
        self.setButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.setButton.setObjectName("setButton")
        self.gridLayout.addWidget(self.setButton, 0, 3, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.stepLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.stepLineEdit.setObjectName("stepLineEdit")
        self.gridLayout.addWidget(self.stepLineEdit, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.infLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.infLineEdit.setObjectName("infLineEdit")
        self.gridLayout.addWidget(self.infLineEdit, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 2, 1, 1)
        self.randomButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomButton.sizePolicy().hasHeightForWidth())
        self.randomButton.setSizePolicy(sizePolicy)
        self.randomButton.setMinimumSize(QtCore.QSize(60, 56))
        self.randomButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.randomButton.setObjectName("randomButton")
        self.gridLayout.addWidget(self.randomButton, 3, 3, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.supLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.supLineEdit.setObjectName("supLineEdit")
        self.gridLayout.addWidget(self.supLineEdit, 4, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.sourceButton.setMinimumSize(QtCore.QSize(80, 30))
        self.sourceButton.setObjectName("sourceButton")
        self.horizontalLayout.addWidget(self.sourceButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setArrowType(QtCore.Qt.DownArrow)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.treeView, self.l2rRadioButton)
        MainWindow.setTabOrder(self.l2rRadioButton, self.randomRadioButton)
        MainWindow.setTabOrder(self.randomRadioButton, self.alignLButton)
        MainWindow.setTabOrder(self.alignLButton, self.alignCButton)
        MainWindow.setTabOrder(self.alignCButton, self.alignRButton)
        MainWindow.setTabOrder(self.alignRButton, self.distributeButton)
        MainWindow.setTabOrder(self.distributeButton, self.absoluteRadioButton)
        MainWindow.setTabOrder(self.absoluteRadioButton, self.relativeRadioButton)
        MainWindow.setTabOrder(self.relativeRadioButton, self.valueLineEdit)
        MainWindow.setTabOrder(self.valueLineEdit, self.stepLineEdit)
        MainWindow.setTabOrder(self.stepLineEdit, self.setButton)
        MainWindow.setTabOrder(self.setButton, self.infLineEdit)
        MainWindow.setTabOrder(self.infLineEdit, self.supLineEdit)
        MainWindow.setTabOrder(self.supLineEdit, self.randomButton)
        MainWindow.setTabOrder(self.randomButton, self.minimizeButton)
        MainWindow.setTabOrder(self.minimizeButton, self.closeButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Oder", None, -1))
        self.l2rRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "LtoR", None, -1))
        self.randomRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "random", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Align", None, -1))
        self.alignRButton.setText(QtWidgets.QApplication.translate("MainWindow", "⇥", None, -1))
        self.alignLButton.setText(QtWidgets.QApplication.translate("MainWindow", "⇤", None, -1))
        self.distributeButton.setText(QtWidgets.QApplication.translate("MainWindow", "|||", None, -1))
        self.alignCButton.setText(QtWidgets.QApplication.translate("MainWindow", "┃", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Input", None, -1))
        self.absoluteRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Absolute", None, -1))
        self.relativeRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Relative", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Value", None, -1))
        self.setButton.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Step", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "inf", None, -1))
        self.randomButton.setText(QtWidgets.QApplication.translate("MainWindow", "Random", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "sup", None, -1))
        self.sourceButton.setText(QtWidgets.QApplication.translate("MainWindow", "source", None, -1))
        self.minimizeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "最小化", None, -1))
        self.minimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.closeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "閉じる", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

