# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\color_tool\color_tool.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\color_tool\color_tool.ui' applies.
#
# Created: Tue Feb 14 06:41:48 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = View(self.centralwidget)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.colormindDefButton = QtWidgets.QPushButton(self.groupBox)
        self.colormindDefButton.setMinimumSize(QtCore.QSize(100, 30))
        self.colormindDefButton.setObjectName("colormindDefButton")
        self.horizontalLayout.addWidget(self.colormindDefButton)
        self.colormindUiButton = QtWidgets.QPushButton(self.groupBox)
        self.colormindUiButton.setMinimumSize(QtCore.QSize(100, 30))
        self.colormindUiButton.setObjectName("colormindUiButton")
        self.horizontalLayout.addWidget(self.colormindUiButton)
        self.useSelectionCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.useSelectionCheckBox.setObjectName("useSelectionCheckBox")
        self.horizontalLayout.addWidget(self.useSelectionCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.openUrlButton = QtWidgets.QPushButton(self.groupBox)
        self.openUrlButton.setMinimumSize(QtCore.QSize(0, 30))
        self.openUrlButton.setObjectName("openUrlButton")
        self.horizontalLayout.addWidget(self.openUrlButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l2rRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.l2rRadioButton.setChecked(True)
        self.l2rRadioButton.setObjectName("l2rRadioButton")
        self.horizontalLayout_3.addWidget(self.l2rRadioButton)
        self.randomRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.randomRadioButton.setObjectName("randomRadioButton")
        self.horizontalLayout_3.addWidget(self.randomRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.currentRowButton = QtWidgets.QPushButton(self.centralwidget)
        self.currentRowButton.setMinimumSize(QtCore.QSize(100, 30))
        self.currentRowButton.setObjectName("currentRowButton")
        self.horizontalLayout_4.addWidget(self.currentRowButton)
        self.selectedButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectedButton.setMinimumSize(QtCore.QSize(100, 30))
        self.selectedButton.setObjectName("selectedButton")
        self.horizontalLayout_4.addWidget(self.selectedButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setArrowType(QtCore.Qt.DownArrow)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_4.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_4.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Colormind", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Add:", None, -1))
        self.colormindDefButton.setText(QtWidgets.QApplication.translate("MainWindow", "model: default", None, -1))
        self.colormindUiButton.setText(QtWidgets.QApplication.translate("MainWindow", "model: ui", None, -1))
        self.useSelectionCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "use selection", None, -1))
        self.openUrlButton.setText(QtWidgets.QApplication.translate("MainWindow", "website", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Oder", None, -1))
        self.l2rRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "LtoR", None, -1))
        self.randomRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "random", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Apply:", None, -1))
        self.currentRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "current row", None, -1))
        self.selectedButton.setText(QtWidgets.QApplication.translate("MainWindow", "selected", None, -1))
        self.minimizeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "最小化", None, -1))
        self.minimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.actionNew.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionOpen.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionSave.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save As", None, -1))
        self.actionSave_As.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))

from rs_fusion.tool.color_tool.color_table import View
