# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\set_pivot\set_pivot.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\set_pivot\set_pivot.ui' applies.
#
# Created: Tue Feb  7 11:39:14 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(167, 324)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(167, 270))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 167, 179))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(167, 179))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nwButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nwButton.sizePolicy().hasHeightForWidth())
        self.nwButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.nwButton.setFont(font)
        self.nwButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.nwButton.setObjectName("nwButton")
        self.gridLayout.addWidget(self.nwButton, 0, 0, 1, 1)
        self.nButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nButton.sizePolicy().hasHeightForWidth())
        self.nButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.nButton.setFont(font)
        self.nButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.nButton.setObjectName("nButton")
        self.gridLayout.addWidget(self.nButton, 0, 1, 1, 1)
        self.neButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neButton.sizePolicy().hasHeightForWidth())
        self.neButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.neButton.setFont(font)
        self.neButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.neButton.setObjectName("neButton")
        self.gridLayout.addWidget(self.neButton, 0, 2, 1, 1)
        self.wButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wButton.sizePolicy().hasHeightForWidth())
        self.wButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.wButton.setFont(font)
        self.wButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.wButton.setObjectName("wButton")
        self.gridLayout.addWidget(self.wButton, 1, 0, 1, 1)
        self.centerButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerButton.sizePolicy().hasHeightForWidth())
        self.centerButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.centerButton.setFont(font)
        self.centerButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.centerButton.setObjectName("centerButton")
        self.gridLayout.addWidget(self.centerButton, 1, 1, 1, 1)
        self.eButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eButton.sizePolicy().hasHeightForWidth())
        self.eButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.eButton.setFont(font)
        self.eButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.eButton.setObjectName("eButton")
        self.gridLayout.addWidget(self.eButton, 1, 2, 1, 1)
        self.swButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swButton.sizePolicy().hasHeightForWidth())
        self.swButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.swButton.setFont(font)
        self.swButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.swButton.setObjectName("swButton")
        self.gridLayout.addWidget(self.swButton, 2, 0, 1, 1)
        self.sButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sButton.sizePolicy().hasHeightForWidth())
        self.sButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.sButton.setFont(font)
        self.sButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.sButton.setObjectName("sButton")
        self.gridLayout.addWidget(self.sButton, 2, 1, 1, 1)
        self.seButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seButton.sizePolicy().hasHeightForWidth())
        self.seButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.seButton.setFont(font)
        self.seButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.seButton.setObjectName("seButton")
        self.gridLayout.addWidget(self.seButton, 2, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 180, 167, 84))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.setButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setButton.sizePolicy().hasHeightForWidth())
        self.setButton.setSizePolicy(sizePolicy)
        self.setButton.setMinimumSize(QtCore.QSize(50, 50))
        self.setButton.setMaximumSize(QtCore.QSize(50, 50))
        self.setButton.setObjectName("setButton")
        self.gridLayout_2.addWidget(self.setButton, 0, 2, 2, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.xLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit.setObjectName("xLineEdit")
        self.gridLayout_2.addWidget(self.xLineEdit, 0, 1, 1, 1)
        self.yLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.yLineEdit.setObjectName("yLineEdit")
        self.gridLayout_2.addWidget(self.yLineEdit, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xIsLockCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.xIsLockCheckBox.setObjectName("xIsLockCheckBox")
        self.horizontalLayout_3.addWidget(self.xIsLockCheckBox)
        self.yIsLockCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.yIsLockCheckBox.setObjectName("yIsLockCheckBox")
        self.horizontalLayout_3.addWidget(self.yIsLockCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setArrowType(QtCore.Qt.DownArrow)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.nwButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡬", None, -1))
        self.nButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡩", None, -1))
        self.neButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡭", None, -1))
        self.wButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡨", None, -1))
        self.centerButton.setText(QtWidgets.QApplication.translate("MainWindow", "●", None, -1))
        self.eButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡪", None, -1))
        self.swButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡯", None, -1))
        self.sButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡫", None, -1))
        self.seButton.setText(QtWidgets.QApplication.translate("MainWindow", "🡮", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.setButton.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.xIsLockCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Lock X", None, -1))
        self.yIsLockCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Lock Y", None, -1))
        self.minimizeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "最小化", None, -1))
        self.minimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.closeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "閉じる", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

