# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\resolve\Python\rs_resolve\tool\playhead\playhead.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\resolve\Python\rs_resolve\tool\playhead\playhead.ui' applies.
#
# Created: Tue Dec 20 11:06:38 2022
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(199, 212)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.num02SpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.num02SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.num02SpinBox.setMaximum(999999999)
        self.num02SpinBox.setObjectName("num02SpinBox")
        self.gridLayout.addWidget(self.num02SpinBox, 1, 0, 1, 1)
        self.subtitleLeftButton = QtWidgets.QToolButton(self.centralwidget)
        self.subtitleLeftButton.setArrowType(QtCore.Qt.LeftArrow)
        self.subtitleLeftButton.setObjectName("subtitleLeftButton")
        self.gridLayout.addWidget(self.subtitleLeftButton, 2, 1, 1, 1)
        self.n02RightButton = QtWidgets.QToolButton(self.centralwidget)
        self.n02RightButton.setArrowType(QtCore.Qt.RightArrow)
        self.n02RightButton.setObjectName("n02RightButton")
        self.gridLayout.addWidget(self.n02RightButton, 1, 2, 1, 1)
        self.subtitleComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.subtitleComboBox.setObjectName("subtitleComboBox")
        self.gridLayout.addWidget(self.subtitleComboBox, 2, 0, 1, 1)
        self.num01SpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.num01SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.num01SpinBox.setMaximum(999999999)
        self.num01SpinBox.setObjectName("num01SpinBox")
        self.gridLayout.addWidget(self.num01SpinBox, 0, 0, 1, 1)
        self.audioRightButton = QtWidgets.QToolButton(self.centralwidget)
        self.audioRightButton.setArrowType(QtCore.Qt.RightArrow)
        self.audioRightButton.setObjectName("audioRightButton")
        self.gridLayout.addWidget(self.audioRightButton, 4, 2, 1, 1)
        self.vidioRightButton = QtWidgets.QToolButton(self.centralwidget)
        self.vidioRightButton.setArrowType(QtCore.Qt.RightArrow)
        self.vidioRightButton.setObjectName("vidioRightButton")
        self.gridLayout.addWidget(self.vidioRightButton, 3, 2, 1, 1)
        self.n01LeftButton = QtWidgets.QToolButton(self.centralwidget)
        self.n01LeftButton.setArrowType(QtCore.Qt.LeftArrow)
        self.n01LeftButton.setObjectName("n01LeftButton")
        self.gridLayout.addWidget(self.n01LeftButton, 0, 1, 1, 1)
        self.subtitleRightButton = QtWidgets.QToolButton(self.centralwidget)
        self.subtitleRightButton.setArrowType(QtCore.Qt.RightArrow)
        self.subtitleRightButton.setObjectName("subtitleRightButton")
        self.gridLayout.addWidget(self.subtitleRightButton, 2, 2, 1, 1)
        self.audioLeftButton = QtWidgets.QToolButton(self.centralwidget)
        self.audioLeftButton.setArrowType(QtCore.Qt.LeftArrow)
        self.audioLeftButton.setObjectName("audioLeftButton")
        self.gridLayout.addWidget(self.audioLeftButton, 4, 1, 1, 1)
        self.n02LeftButton = QtWidgets.QToolButton(self.centralwidget)
        self.n02LeftButton.setArrowType(QtCore.Qt.LeftArrow)
        self.n02LeftButton.setObjectName("n02LeftButton")
        self.gridLayout.addWidget(self.n02LeftButton, 1, 1, 1, 1)
        self.vidioLeftButton = QtWidgets.QToolButton(self.centralwidget)
        self.vidioLeftButton.setArrowType(QtCore.Qt.LeftArrow)
        self.vidioLeftButton.setObjectName("vidioLeftButton")
        self.gridLayout.addWidget(self.vidioLeftButton, 3, 1, 1, 1)
        self.audioComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.audioComboBox.setObjectName("audioComboBox")
        self.gridLayout.addWidget(self.audioComboBox, 4, 0, 1, 1)
        self.n01RightButton = QtWidgets.QToolButton(self.centralwidget)
        self.n01RightButton.setArrowType(QtCore.Qt.RightArrow)
        self.n01RightButton.setObjectName("n01RightButton")
        self.gridLayout.addWidget(self.n01RightButton, 0, 2, 1, 1)
        self.videoComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.videoComboBox.setObjectName("videoComboBox")
        self.gridLayout.addWidget(self.videoComboBox, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.timelineLeftButton = QtWidgets.QToolButton(self.centralwidget)
        self.timelineLeftButton.setArrowType(QtCore.Qt.LeftArrow)
        self.timelineLeftButton.setObjectName("timelineLeftButton")
        self.gridLayout.addWidget(self.timelineLeftButton, 5, 1, 1, 1)
        self.timelineRightButton = QtWidgets.QToolButton(self.centralwidget)
        self.timelineRightButton.setArrowType(QtCore.Qt.RightArrow)
        self.timelineRightButton.setObjectName("timelineRightButton")
        self.gridLayout.addWidget(self.timelineRightButton, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setMinimumSize(QtCore.QSize(50, 30))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setArrowType(QtCore.Qt.DownArrow)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(50, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.subtitleLeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.n02RightButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.audioRightButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.vidioRightButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.n01LeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.subtitleRightButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.audioLeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.n02LeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.vidioLeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.n01RightButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Timeline", None, -1))
        self.timelineLeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.timelineRightButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.updateButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "トラック更新", None, -1))
        self.updateButton.setText(QtWidgets.QApplication.translate("MainWindow", "update", None, -1))
        self.minimizeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "最小化", None, -1))
        self.minimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.closeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "閉じる", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

