# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\importer\importer.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\importer\importer.ui' applies.
#
# Created: Fri Jun 16 08:30:10 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(269, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.jsonLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.jsonLineEdit.setObjectName("jsonLineEdit")
        self.horizontalLayout_2.addWidget(self.jsonLineEdit)
        self.jsonToolButton = QtWidgets.QToolButton(self.groupBox_2)
        self.jsonToolButton.setObjectName("jsonToolButton")
        self.horizontalLayout_2.addWidget(self.jsonToolButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.expRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.expRadioButton.setObjectName("expRadioButton")
        self.verticalLayout_3.addWidget(self.expRadioButton)
        self.connectRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.connectRadioButton.setObjectName("connectRadioButton")
        self.verticalLayout_3.addWidget(self.connectRadioButton)
        self.connectLabelRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.connectLabelRadioButton.setObjectName("connectLabelRadioButton")
        self.verticalLayout_3.addWidget(self.connectLabelRadioButton)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.btnSizeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.btnSizeSpinBox.setObjectName("btnSizeSpinBox")
        self.horizontalLayout_4.addWidget(self.btnSizeSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.xSpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSpinBox.sizePolicy().hasHeightForWidth())
        self.xSpinBox.setSizePolicy(sizePolicy)
        self.xSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xSpinBox.setMaximum(999999999)
        self.xSpinBox.setObjectName("xSpinBox")
        self.horizontalLayout.addWidget(self.xSpinBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ySpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ySpinBox.sizePolicy().hasHeightForWidth())
        self.ySpinBox.setSizePolicy(sizePolicy)
        self.ySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ySpinBox.setMaximum(999999999)
        self.ySpinBox.setObjectName("ySpinBox")
        self.horizontalLayout.addWidget(self.ySpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.useMMCheckBox = QtWidgets.QCheckBox(self.tab_2)
        self.useMMCheckBox.setObjectName("useMMCheckBox")
        self.verticalLayout_5.addWidget(self.useMMCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 146, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setMinimumSize(QtCore.QSize(80, 30))
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_3.addWidget(self.importButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "ファイル", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "JSON", None, -1))
        self.jsonToolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "立ち絵形式", None, -1))
        self.expRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "エクスプレッション", None, -1))
        self.connectRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "コネクション切り替え(Page)", None, -1))
        self.connectLabelRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "コネクション切り替え(Label)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "※エクスプレッションが従来のものです。", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "コネクション切り替え式オプション", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "通常ボタン サイズ", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "拡張 (アニメーション スペース確保)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.xSpinBox.setSuffix(QtWidgets.QApplication.translate("MainWindow", " px", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.ySpinBox.setSuffix(QtWidgets.QApplication.translate("MainWindow", " px", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "立ち絵", None, -1))
        self.useMMCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "MultiMerge", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "通常", None, -1))
        self.importButton.setText(QtWidgets.QApplication.translate("MainWindow", "import", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

