# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\center_tool\center_tool.ui',
# licensing of 'C:\Users\yoshi\PycharmProjects\Resolve_Script\app\fusion\python\rs_fusion\tool\center_tool\center_tool.ui' applies.
#
# Created: Fri Mar  3 07:18:35 2023
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(298, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l2rRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.l2rRadioButton.setChecked(True)
        self.l2rRadioButton.setObjectName("l2rRadioButton")
        self.horizontalLayout_3.addWidget(self.l2rRadioButton)
        self.randomRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.randomRadioButton.setObjectName("randomRadioButton")
        self.horizontalLayout_3.addWidget(self.randomRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(280, 140))
        self.groupBox_3.setMaximumSize(QtCore.QSize(280, 140))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.distributeVButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distributeVButton.sizePolicy().hasHeightForWidth())
        self.distributeVButton.setSizePolicy(sizePolicy)
        self.distributeVButton.setMinimumSize(QtCore.QSize(45, 45))
        self.distributeVButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.distributeVButton.setFont(font)
        self.distributeVButton.setStyleSheet("font:16pt \"メイリオ\";")
        self.distributeVButton.setObjectName("distributeVButton")
        self.gridLayout.addWidget(self.distributeVButton, 0, 3, 1, 1)
        self.distributeHButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distributeHButton.sizePolicy().hasHeightForWidth())
        self.distributeHButton.setSizePolicy(sizePolicy)
        self.distributeHButton.setMinimumSize(QtCore.QSize(45, 45))
        self.distributeHButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.distributeHButton.setFont(font)
        self.distributeHButton.setStyleSheet("font: 24pt \"メイリオ\";")
        self.distributeHButton.setObjectName("distributeHButton")
        self.gridLayout.addWidget(self.distributeHButton, 1, 3, 1, 1)
        self.alignLButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLButton.sizePolicy().hasHeightForWidth())
        self.alignLButton.setSizePolicy(sizePolicy)
        self.alignLButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignLButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignLButton.setFont(font)
        self.alignLButton.setStyleSheet("font:24pt \"メイリオ\";")
        self.alignLButton.setObjectName("alignLButton")
        self.gridLayout.addWidget(self.alignLButton, 0, 0, 1, 1)
        self.alignHCButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignHCButton.sizePolicy().hasHeightForWidth())
        self.alignHCButton.setSizePolicy(sizePolicy)
        self.alignHCButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignHCButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignHCButton.setFont(font)
        self.alignHCButton.setStyleSheet("font: 16pt \"メイリオ\";")
        self.alignHCButton.setObjectName("alignHCButton")
        self.gridLayout.addWidget(self.alignHCButton, 1, 1, 1, 1)
        self.alignTButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignTButton.sizePolicy().hasHeightForWidth())
        self.alignTButton.setSizePolicy(sizePolicy)
        self.alignTButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignTButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignTButton.setFont(font)
        self.alignTButton.setStyleSheet("font:24pt \"メイリオ\";")
        self.alignTButton.setObjectName("alignTButton")
        self.gridLayout.addWidget(self.alignTButton, 1, 0, 1, 1)
        self.alignVCButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignVCButton.sizePolicy().hasHeightForWidth())
        self.alignVCButton.setSizePolicy(sizePolicy)
        self.alignVCButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignVCButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignVCButton.setFont(font)
        self.alignVCButton.setStyleSheet("font: 16pt \"メイリオ\";")
        self.alignVCButton.setObjectName("alignVCButton")
        self.gridLayout.addWidget(self.alignVCButton, 0, 1, 1, 1)
        self.alignBButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignBButton.sizePolicy().hasHeightForWidth())
        self.alignBButton.setSizePolicy(sizePolicy)
        self.alignBButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignBButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignBButton.setFont(font)
        self.alignBButton.setStyleSheet("font:24pt \"メイリオ\";")
        self.alignBButton.setObjectName("alignBButton")
        self.gridLayout.addWidget(self.alignBButton, 1, 2, 1, 1)
        self.alignRButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignRButton.sizePolicy().hasHeightForWidth())
        self.alignRButton.setSizePolicy(sizePolicy)
        self.alignRButton.setMinimumSize(QtCore.QSize(45, 45))
        self.alignRButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.alignRButton.setFont(font)
        self.alignRButton.setStyleSheet("font:24pt \"メイリオ\";")
        self.alignRButton.setObjectName("alignRButton")
        self.gridLayout.addWidget(self.alignRButton, 0, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.useDodCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.useDodCheckBox.setObjectName("useDodCheckBox")
        self.verticalLayout_3.addWidget(self.useDodCheckBox)
        self.useCanvasCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.useCanvasCheckBox.setObjectName("useCanvasCheckBox")
        self.verticalLayout_3.addWidget(self.useCanvasCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(280, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.absoluteRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.absoluteRadioButton.setChecked(True)
        self.absoluteRadioButton.setObjectName("absoluteRadioButton")
        self.horizontalLayout_4.addWidget(self.absoluteRadioButton)
        self.relativeRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.relativeRadioButton.setObjectName("relativeRadioButton")
        self.horizontalLayout_4.addWidget(self.relativeRadioButton)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.yLineEdit.setObjectName("yLineEdit")
        self.gridLayout_2.addWidget(self.yLineEdit, 2, 1, 1, 1)
        self.setYButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setYButton.sizePolicy().hasHeightForWidth())
        self.setYButton.setSizePolicy(sizePolicy)
        self.setYButton.setMinimumSize(QtCore.QSize(50, 50))
        self.setYButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.setYButton.setObjectName("setYButton")
        self.gridLayout_2.addWidget(self.setYButton, 2, 3, 2, 1)
        self.yStepLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.yStepLineEdit.setObjectName("yStepLineEdit")
        self.gridLayout_2.addWidget(self.yStepLineEdit, 3, 1, 1, 1)
        self.ySupLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.ySupLineEdit.setObjectName("ySupLineEdit")
        self.gridLayout_2.addWidget(self.ySupLineEdit, 8, 1, 1, 1)
        self.xInfLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.xInfLineEdit.setObjectName("xInfLineEdit")
        self.gridLayout_2.addWidget(self.xInfLineEdit, 5, 1, 1, 1)
        self.randomYButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomYButton.sizePolicy().hasHeightForWidth())
        self.randomYButton.setSizePolicy(sizePolicy)
        self.randomYButton.setMinimumSize(QtCore.QSize(50, 50))
        self.randomYButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.randomYButton.setObjectName("randomYButton")
        self.gridLayout_2.addWidget(self.randomYButton, 7, 3, 2, 1)
        self.randomXButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomXButton.sizePolicy().hasHeightForWidth())
        self.randomXButton.setSizePolicy(sizePolicy)
        self.randomXButton.setMinimumSize(QtCore.QSize(50, 50))
        self.randomXButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.randomXButton.setObjectName("randomXButton")
        self.gridLayout_2.addWidget(self.randomXButton, 5, 3, 2, 1)
        self.xStepLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.xStepLineEdit.setObjectName("xStepLineEdit")
        self.gridLayout_2.addWidget(self.xStepLineEdit, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.xSupLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.xSupLineEdit.setObjectName("xSupLineEdit")
        self.gridLayout_2.addWidget(self.xSupLineEdit, 6, 1, 1, 1)
        self.yInfLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.yInfLineEdit.setObjectName("yInfLineEdit")
        self.gridLayout_2.addWidget(self.yInfLineEdit, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.setXButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setXButton.sizePolicy().hasHeightForWidth())
        self.setXButton.setSizePolicy(sizePolicy)
        self.setXButton.setMinimumSize(QtCore.QSize(50, 50))
        self.setXButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.setXButton.setObjectName("setXButton")
        self.gridLayout_2.addWidget(self.setXButton, 0, 3, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 8, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 2, 1, 1)
        self.randomButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomButton.sizePolicy().hasHeightForWidth())
        self.randomButton.setSizePolicy(sizePolicy)
        self.randomButton.setMinimumSize(QtCore.QSize(60, 106))
        self.randomButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.randomButton.setObjectName("randomButton")
        self.gridLayout_2.addWidget(self.randomButton, 5, 4, 4, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 6, 2, 1, 1)
        self.xLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit.setObjectName("xLineEdit")
        self.gridLayout_2.addWidget(self.xLineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.setButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setButton.sizePolicy().hasHeightForWidth())
        self.setButton.setSizePolicy(sizePolicy)
        self.setButton.setMinimumSize(QtCore.QSize(60, 106))
        self.setButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.setButton.setObjectName("setButton")
        self.gridLayout_2.addWidget(self.setButton, 0, 4, 4, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 5, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem11, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.minimizeButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setArrowType(QtCore.Qt.DownArrow)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 30))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.l2rRadioButton, self.randomRadioButton)
        MainWindow.setTabOrder(self.randomRadioButton, self.alignLButton)
        MainWindow.setTabOrder(self.alignLButton, self.alignVCButton)
        MainWindow.setTabOrder(self.alignVCButton, self.alignRButton)
        MainWindow.setTabOrder(self.alignRButton, self.distributeVButton)
        MainWindow.setTabOrder(self.distributeVButton, self.alignTButton)
        MainWindow.setTabOrder(self.alignTButton, self.alignHCButton)
        MainWindow.setTabOrder(self.alignHCButton, self.alignBButton)
        MainWindow.setTabOrder(self.alignBButton, self.distributeHButton)
        MainWindow.setTabOrder(self.distributeHButton, self.absoluteRadioButton)
        MainWindow.setTabOrder(self.absoluteRadioButton, self.relativeRadioButton)
        MainWindow.setTabOrder(self.relativeRadioButton, self.xLineEdit)
        MainWindow.setTabOrder(self.xLineEdit, self.xStepLineEdit)
        MainWindow.setTabOrder(self.xStepLineEdit, self.setXButton)
        MainWindow.setTabOrder(self.setXButton, self.yLineEdit)
        MainWindow.setTabOrder(self.yLineEdit, self.yStepLineEdit)
        MainWindow.setTabOrder(self.yStepLineEdit, self.setYButton)
        MainWindow.setTabOrder(self.setYButton, self.setButton)
        MainWindow.setTabOrder(self.setButton, self.xInfLineEdit)
        MainWindow.setTabOrder(self.xInfLineEdit, self.xSupLineEdit)
        MainWindow.setTabOrder(self.xSupLineEdit, self.randomXButton)
        MainWindow.setTabOrder(self.randomXButton, self.yInfLineEdit)
        MainWindow.setTabOrder(self.yInfLineEdit, self.ySupLineEdit)
        MainWindow.setTabOrder(self.ySupLineEdit, self.randomYButton)
        MainWindow.setTabOrder(self.randomYButton, self.randomButton)
        MainWindow.setTabOrder(self.randomButton, self.minimizeButton)
        MainWindow.setTabOrder(self.minimizeButton, self.closeButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Oder", None, -1))
        self.l2rRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "LtoR", None, -1))
        self.randomRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "random", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Align", None, -1))
        self.distributeVButton.setText(QtWidgets.QApplication.translate("MainWindow", "|||", None, -1))
        self.distributeHButton.setText(QtWidgets.QApplication.translate("MainWindow", "≡", None, -1))
        self.alignLButton.setText(QtWidgets.QApplication.translate("MainWindow", "⇤", None, -1))
        self.alignHCButton.setText(QtWidgets.QApplication.translate("MainWindow", "━", None, -1))
        self.alignTButton.setText(QtWidgets.QApplication.translate("MainWindow", "⤒", None, -1))
        self.alignVCButton.setText(QtWidgets.QApplication.translate("MainWindow", "┃", None, -1))
        self.alignBButton.setText(QtWidgets.QApplication.translate("MainWindow", "⤓", None, -1))
        self.alignRButton.setText(QtWidgets.QApplication.translate("MainWindow", "⇥", None, -1))
        self.useDodCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "DoD", None, -1))
        self.useCanvasCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Canvas", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Input", None, -1))
        self.absoluteRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Absolute", None, -1))
        self.relativeRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Relative", None, -1))
        self.setYButton.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.randomYButton.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.randomXButton.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Step", None, -1))
        self.setXButton.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.randomButton.setText(QtWidgets.QApplication.translate("MainWindow", "Random", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "sup", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Step", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "inf", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "sup", None, -1))
        self.setButton.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "inf ", None, -1))
        self.minimizeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "最小化", None, -1))
        self.minimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.closeButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "閉じる", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "close", None, -1))

